### ISSUE TITLE
Getting "message": "access_denied: Unauthorized"

### ISSUE THREAD

**Issue by ankur6ue** [auth0-samples/auth0-python-web-app#62]
I'm able to successfully login and have my callback URL called, with a valid looking code token. However I'm getting a 

```
{
  "message": "access_denied: Unauthorized"
}
```
In 
```
auth0.authorize_access_token()
```
in the callback function.

The logs say "failed exchange" with the following details:
```
{
  "date": "2021-11-02T03:18:02.729Z",
  "type": "feacft",
  "description": "Unauthorized",
  "connection_id": "",
  "client_id": null,
  "client_name": null,
  "ip": "108.28.73.248",
  "user_agent": "Other 0.0.0 / Other 0.0.0",
  "details": {
    "code": "******************************************G1M"
  },
  "hostname": "dev--i****pk.us.auth0.com",
  "user_id": "",
  "user_name": "",
  "log_id": "90020211102031805905893429383434853960365843545617072130",
  "_id": "90020211102031805905893429383434853960365843545617072130",
  "isMobile": false
}
```

The application type is "Native" with Token Endpoint Authentication Method of "None". I didn't change any of the other defaults other than setting the AUTH0_CLIENT_ID, AUTH0_CALLBACK_URL and other variables in the Python code and making the corresponding changes in the app settings..

Please help!

**Comment by wintermute-cell** [comment]
Facing the same issue, any updates?

**Comment by willronchetti** [comment]
Facing the same issue as well.

**Comment by evansims** [comment]
Hey everyone 👋 As @willronchetti mentioned, this would be due to a misconfiguration of some type, either with your sample app or the Auth0 client configuration. You'll want to review your Auth0 logs (accessible from https://manage.auth0.com/) for guidance on what is triggering the error. You can also reach out to the Auth0 community at https://community.auth0.com with questions.

We'll be closing this issue as it's been open for quite some time and is a bit stale; however, if you have further questions or need further help, don't hesitate to create a new issue or ask in the Community.
